export const report = {
  syncDelegatesSpentTime: 0,
  syncProjectsSpentTime: 0,
  syncDonationsSpentTime: 0,
  syncPledgeAdminsSpentTime: 0,
  syncMilestoneSpentTime: 0,
  createdDacs: 0,
  createdCampaigns: 0,
  createdMilestones: 0,
  createdDonations: 0,
  updatedDonations: 0,
  updatedDonationsParent: 0,
  updatedDonationsMined: 0,
  updateAmountRemaining: 0,
  deletedDonations: 0,
  createdPledgeAdmins: 0,
  updatedMilestoneStatus: 0,
  processedEvents: 0,
  correctFailedDonations: 0,
  fetchedNewEventsCount: 0,
  fetchedNewPledgeAdminCount: 0,
  fetchedNewPledgeCount: 0,
  removedPendingAmountRemainingCount: 0
};
