name:  CI/CD

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: install dependencies
        run: npm install
      - name: run linter
        run: npm run lint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
  deploy:
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: develop deploy
        if: github.ref == 'refs/heads/develop'
        uses: garygrossgarten/github-action-ssh@v0.6.4
        with:
          command: cd giveth-1-simulation && git checkout develop && git pull origin develop && [[ -s $HOME/.nvm/nvm.sh ]] && . $HOME/.nvm/nvm.sh && nvm use 10  && npm ci && npm run build
          host: ${{ secrets.DEVELOP_HOST }}
          username: ${{ secrets.DEVELOP_USERNAME }}
#          passphrase: ${{ secrets.PASSPHRASE }}
          privateKey: ${{ secrets.DEVELOP_PRIVATE_KEY}}

      - name: beta deploy
        if: github.ref == 'refs/heads/master'
        uses: garygrossgarten/github-action-ssh@v0.6.4
        with:
          command: cd giveth-1-simulation && git checkout master && git pull origin master && [[ -s $HOME/.nvm/nvm.sh ]] && . $HOME/.nvm/nvm.sh && nvm use 10  && npm ci && npm run build
          host: ${{ secrets.BETA_HOST }}
          username: ${{ secrets.BETA_USERNAME }}
#          passphrase: ${{ secrets.PASSPHRASE }}
          privateKey: ${{ secrets.BETA_PRIVATE_KEY}}